<?php
// Heading
$_['text_home ']    = 'Home';
$_['heading_title']    = 'Purpletree Multivendor Settings';
$_['vendor_heading']    = 'Vendor settings';
$_['order_heading']    = 'Order settings';
$_['seller_product_heading']    = 'Seller product settings';
$_['seller_review_heading']    = 'Seller review settings';
$_['seller_contact_heading']    = 'Seller contact settings';
$_['seller_email_heading']    = 'Seller email templates';
$_['seller_store_heading']    = 'Seller store options';

$_['text_extension']   = 'Extensions';
$_['text_success']     = 'Success: You have modified Purpletree Multivendor settings!';
$_['text_edit']        = 'Edit Purpletree Multivendor Settings';
$_['text_yes']        = 'Yes';
$_['text_no']        = 'No';
$_['text_allowed_categories']        = 'Allow all categories';
$_['text_selected_categories']        = 'Allow selected categories';
$_['text_store_email']        = 'Store email';
$_['text_store_phone']        = 'Store phone';
$_['text_store_address']        = 'Store address';
$_['text_seller_logedin']        = 'Logged In';
$_['text_seller_general']        = 'General';

$_['text_assign_categories']        = 'Some products assign to this category please disable them then remove.';

////////category for sing seller product/////
$_['entry_commission'] = 'Commission (in percent per product sale)';
$_['entry_commission_status'] = 'Admin Status for which Commission will calculate';
$_['entry_seller_product_category'] = ' No. of categories allow for a single product';
$_['text_multiple']        = 'Multiple';
$_['text_single']        = 'Single';
/////////////////

$_['please_select'] = '--Please Select--';
$_['error_commission_status'] = 'This field is required!';
$_['entry_seller_manage_order'] = 'Allow seller to manage orders';
$_['entry_seller_approval'] = 'Seller approval required';
$_['entry_product_approval'] = 'Product approval required';
$_['entry_product_edit_approval'] = 'Product edit approval required';
$_['entry_allow_category'] = 'Allow category for seller';
$_['entry_become_seller'] = 'Become seller on signup page';
$_['entry_order_approval'] = 'Order approval required';
$_['entry_seller_review'] = 'Seller review enabled';
$_['entry_seller_contact'] = 'Seller contact mode';
$_['entry_seller_store']        = 'Fields to show';
$_['entry_seller_invoice']        = 'Invoice/shipping generated by seller';

// Entry
$_['entry_status']            = 'Status';
$_['entry_order_id']          = 'Order ID';
$_['entry_email_id']          = 'Email ID';
$_['please_wait']             = 'Please wait..';

// Error
$_['error_permission'] = 'Warning: You do not have permission to modify Purpletree Multivendor Settings!';
$_['error_commission'] = 'Please enter valid commission!';
$_['error_product_limit'] = 'Please enter product limit!';
$_['error_process_data'] = 'License key is required!';
$_['error_order_id'] = 'Enter valid Order Id!';
$_['error_email_id'] = 'Enter valid e-mail address!';
$_['error_Enter_license_key'] ="Enter license key";
$_['allow_browse_sellers'] ="Enable Browse Sellers";
$_['entry_allow_metals'] = 'Allow seller to add metals product';
$_['entry_limit_purchase'] = 'Max. number of seller products allowed in cart';
//button
$_['dont_have_lisence_key'] = 'Dont Have License Key'; 
$_['enter_license_key1'] = 'Enter License Key';
$_['button_get_license'] = 'Get License';
$_['button_submit'] = 'Submit';
$_['button_ok'] = 'OK';
$_['change_license_key'] = 'Change License Key';
$_['error_tax_value'] = 'Enter Valid Tax Value';
$_['error_tax_name'] = 'Enter Valid Tax Name';
$_['grace_period_error'] = 'Enter Valid Grace Period';
$_['reminder_one_days_error'] = 'Enter Valid Reminder Days';
$_['reminder_two_days_error'] = 'Enter Valid Reminder Days';
$_['reminder_three_days_error'] = 'Enter Valid Reminder Days';
$_['error_shipping_commission'] = 'Please enter valid shipping commission!';


